apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: carebridge-postgres
  namespace: carebridge
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: carebridge-postgres
  namespace: carebridge
$patch: delete
